### ISSUE TITLE
如何关闭格式化 How do I turn off formatting

### ISSUE THREAD

**Issue by BoltDoggy** [merrihew/atom-jade#1]
复制粘贴时会自动格式化，但是缩进是有误的.

Automatic formatting when you copy-and-paste, but the indentation is wrong.

**Comment by merrihew** [comment]
@lc60005457 Unclear what you're asking here, can you please explain? Feel free to open up a PR to fix the issue.

**Comment by jerone** [comment]
Dup: https://github.com/merrihew/atom-jade/issues/34

**Comment by BoltDoggy** [comment]
@jerone thankyou
